from enum import Enum


class Platform(str, Enum):
    MOCK = "MOCK"
    XIAOHONGSHU = "XIAOHONGSHU"
    DOUYIN = "DOUYIN"
    WECHAT_CHANNELS = "WECHAT_CHANNELS"


class CapabilityStatus(str, Enum):
    SUPPORTED = "SUPPORTED"
    CONDITIONAL = "CONDITIONAL"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    MANUAL = "MANUAL"
    UNSUPPORTED = "UNSUPPORTED"
    UNKNOWN = "UNKNOWN"
    RATE_LIMITED = "RATE_LIMITED"
    DISABLED = "DISABLED"


class CapabilityName(str, Enum):
    CREATOR_MONITORING = "CREATOR_MONITORING"
    NEW_POST_WEBHOOK = "NEW_POST_WEBHOOK"
    LATEST_POSTS = "LATEST_POSTS"
    POST_FETCH = "POST_FETCH"
    COMMENT_READ = "COMMENT_READ"
    TOP_LEVEL_COMMENT = "TOP_LEVEL_COMMENT"
    COMMENT_REPLY = "COMMENT_REPLY"
    COMMENT_DELETE = "COMMENT_DELETE"
    COMMENT_CREATED_AT = "COMMENT_CREATED_AT"
    CHRONOLOGICAL_RANK = "CHRONOLOGICAL_RANK"
    VISIBLE_RANK = "VISIBLE_RANK"
    AI_DISCLOSURE = "AI_DISCLOSURE"


class CreatorRelationship(str, Enum):
    OWN_ACCOUNT = "OWN_ACCOUNT"
    PARTNER_CREATOR = "PARTNER_CREATOR"
    OFFICIAL_CAMPAIGN_CREATOR = "OFFICIAL_CAMPAIGN_CREATOR"
    GENERAL_CREATOR = "GENERAL_CREATOR"
    BRAND_ACCOUNT = "BRAND_ACCOUNT"
    COMPETITOR = "COMPETITOR"
    BLOCKED_CREATOR = "BLOCKED_CREATOR"


class AccountKind(str, Enum):
    BRAND_OFFICIAL = "BRAND_OFFICIAL"
    EMPLOYEE_DISCLOSED = "EMPLOYEE_DISCLOSED"
    PARTNER_CREATOR = "PARTNER_CREATOR"
    HUMAN_OPERATOR = "HUMAN_OPERATOR"


class ContentProvenance(str, Enum):
    HUMAN_AUTHORED = "HUMAN_AUTHORED"
    AI_GENERATED_PENDING_REVIEW = "AI_GENERATED_PENDING_REVIEW"
    AI_ASSISTED_HUMAN_EDITED = "AI_ASSISTED_HUMAN_EDITED"
    AI_GENERATED_HUMAN_APPROVED = "AI_GENERATED_HUMAN_APPROVED"
    AI_GENERATED_AUTO_APPROVED = "AI_GENERATED_AUTO_APPROVED"


class DisclosureStatus(str, Enum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED_PENDING = "REQUIRED_PENDING"
    DECLARED = "DECLARED"
    PLATFORM_APPLIED = "PLATFORM_APPLIED"
    UNKNOWN = "UNKNOWN"


class CommentStrategy(str, Enum):
    NORMAL_INTERACTION = "NORMAL_INTERACTION"
    EXPERT_COMMENT = "EXPERT_COMMENT"
    LIGHT_BRAND_MENTION = "LIGHT_BRAND_MENTION"
    PARTNER_BRAND_COMMENT = "PARTNER_BRAND_COMMENT"
    PRODUCT_RELATED = "PRODUCT_RELATED"
    CAMPAIGN_DISCLOSURE = "CAMPAIGN_DISCLOSURE"
    SKIP = "SKIP"


class RunMode(str, Enum):
    NORMAL = "NORMAL"
    FAST = "FAST"
    FIRST_COMMENT = "FIRST_COMMENT"
    TOP5_COMMENT = "TOP5_COMMENT"


class RiskDecision(str, Enum):
    ALLOW = "ALLOW"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"


class QualityDecision(str, Enum):
    ALLOW = "ALLOW"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"
    REGENERATE = "REGENERATE"


class CommentJobState(str, Enum):
    DISCOVERED = "DISCOVERED"
    FETCHING = "FETCHING"
    ANALYZING = "ANALYZING"
    SKIPPED = "SKIPPED"
    GENERATING = "GENERATING"
    QUALITY_CHECKING = "QUALITY_CHECKING"
    RISK_CHECKING = "RISK_CHECKING"
    WAITING_REVIEW = "WAITING_REVIEW"
    READY = "READY"
    WAITING_MANUAL_PUBLISH = "WAITING_MANUAL_PUBLISH"
    PUBLISHING = "PUBLISHING"
    PUBLISH_UNCERTAIN = "PUBLISH_UNCERTAIN"
    READY_FOR_RETRY = "READY_FOR_RETRY"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class PublishMode(str, Enum):
    OFFICIAL_API = "OFFICIAL_API"
    OFFICIAL_PARTNER = "OFFICIAL_PARTNER"
    MANUAL = "MANUAL"
    UNSUPPORTED = "UNSUPPORTED"


class RankConfidence(str, Enum):
    EXACT = "EXACT"
    ESTIMATED = "ESTIMATED"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"


class BrandStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"


class CampaignStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ENDED = "ENDED"


class AuthStatus(str, Enum):
    UNCONFIGURED = "UNCONFIGURED"
    PENDING = "PENDING"
    VALID = "VALID"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"
    ERROR = "ERROR"


class MonitorState(str, Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ERROR = "ERROR"


class PostStatus(str, Enum):
    ACTIVE = "ACTIVE"
    DELETED = "DELETED"
    UNKNOWN = "UNKNOWN"


class AnchorType(str, Enum):
    OBJECT = "OBJECT"
    COLOR = "COLOR"
    STYLE = "STYLE"
    TOPIC = "TOPIC"
    QUOTE = "QUOTE"
    ACTION = "ACTION"
    CLAIM = "CLAIM"


class ClaimStatus(str, Enum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class CandidateStatus(str, Enum):
    GENERATED = "GENERATED"
    SELECTED = "SELECTED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"


class ReviewStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    EDITED_APPROVED = "EDITED_APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    BRAND_MANAGER = "BRAND_MANAGER"
    REVIEWER = "REVIEWER"
    VIEWER = "VIEWER"


class UserStatus(str, Enum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class ActorType(str, Enum):
    USER = "USER"
    SYSTEM = "SYSTEM"
    WORKER = "WORKER"


class DeadLetterStatus(str, Enum):
    PENDING = "PENDING"
    REQUEUED = "REQUEUED"
    RESOLVED = "RESOLVED"


class TenantStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"


class MetricValueType(str, Enum):
    COUNTER = "COUNTER"
    GAUGE = "GAUGE"
    DURATION = "DURATION"
